name: 'GitVersion'
description: 'Generates a Semantic Version number based on your Git history'
outputs:
  major:
    description: "GitVersion Major"
    value: ${{ steps.gitversion.outputs.Major }}
  minor:
    description: "GitVersion Minor"
    value: ${{ steps.gitversion.outputs.Minor }}
  patch:
    description: "GitVersion Patch"
    value: ${{ steps.gitversion.outputs.Patch }}
  pre_release_number:
    description: "GitVersion PreReleaseNumber"
    value: ${{ steps.gitversion.outputs.PreReleaseNumber }}
  major_minor_patch:
    description: "GitVersion MajorMinorPatch"
    value: ${{ steps.gitversion.outputs.MajorMinorPatch }}
  sem_ver:
    description: "GitVersion SemVer"
    value: ${{ steps.gitversion.outputs.SemVer }}
  escaped_branch_name:
    description: "GitVersion EscapedBranchName"
    value: ${{ steps.gitversion.outputs.EscapedBranchName }}
  short_sha:
    description: "GitVersion ShortSha"
    value: ${{ steps.gitversion.outputs.ShortSha }}
runs:
  using: "composite"
  steps:
    - name: Set up .NET cli
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Set up GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0