name: Auto DevOps Workflow

on:
  workflow_call:
    inputs:
      project_name:
        type: string
        required: false
        default: ""
      project_management:
        type: string
        required: false
        default: ""
      project_namespace:
        type: string
        required: false
        default: ""
    secrets:
      nexus_password:
        required: true
      sonar_token:
        required: true
      
jobs:
  setup:
    name: setup
    uses: ./.github/workflows/setup.yml
  maven:
    if: ${{ needs.setup.project_management == 'maven' }}
    name: maven
    uses: ./.github/workflows/maven.yml
    needs:
      - setup
  yarn:
    if: ${{ needs.setup.project_management == 'yarn' }}
    name: yarn
    uses: ./.github/workflows/yarn.yml
    needs:
      - setup
  docker:
    if: ${{ !inputs.docker_enabled }}
    name: docker
    uses: ./.github/workflows/docker.yml
    needs:
      - setup
      - maven
      - yarn