name: Auto DevOps Workflow

on:
  workflow_call:
    inputs:
      project_name:
        type: string
        required: false
        default: ""
      project_language:
        type: string
        required: false
        default: ""
      project_namespace:
        type: string
        required: false
        default: ""
      
jobs:
  setup:
    name: setup
    uses: ./.github/workflows/jobs/setup.yml
  maven:
    name: maven
    uses: ./.github/workflows/jobs/maven.yml