name: Auto DevOps Workflow

run-name: teste auto-devops

on:
  workflow_call:
    inputs:
      project_name:
        type: string
        required: false
        default: ''
      project_buildpack:
        type: string
        required: false
        default: ''
      tests_disabled:
        type: boolean
        required: false
        default: false
      build_artifact_disabled:
        type: boolean
        required: false
        default: false
      build_docker_disabled:
        type: boolean
        required: false
        default: false

jobs:
  setup:
    name: setup
    uses: ./.github/workflows/setup.yml
    with:
      project_name: ${{ inputs.project_name }}
      project_buildpack: ${{ inputs.project_buildpack }}
  tests:
    if: ${{ !inputs.tests_disabled }}
    name: tests
    uses: ./.github/workflows/tests.yml
    needs:
      - setup
  # build_artifact:
  #   if: ${{ !inputs.build_artifact_disabled }}
  #   name: build artifact
  #   uses: ./.github/workflows/build-artifact.yml
  #   needs:
  #     - setup
  #     - tests
  # build_docker:
  #   if: ${{ !inputs.build_docker_disabled }}
  #   name: build docker
  #   uses: ./.github/workflows/build-docker.yml
  #   needs:
  #     - setup
  #     - tests
  #     - build_artifact