name: Build

on:
  workflow_call:
    inputs:
      app_version:
        type: string
        required: false
      build_disabled:
        type: boolean
        required: false
        default: true
      jdk_version:
        type: string
        required: false
        default: "11"
      language:
        type: string
        required: false
      node_package_manager:
        type: string
        required: false
        default: 'yarn'
      node_version:
        type: string
        required: false
        default: "lts/*"
      php_version:
        type: string
        required: false
        default: "latest"

env:
  RUNS_ON: eks-live
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2- Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-B -e -fae -V"

jobs:
  build:
    name: Build
    runs-on: ${{ env.RUNS_ON }}
    if: ${{ !inputs.build_disabled }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        if: ${{ inputs.language == "java" }}
        with:
          java-version: ${{ inputs.jdk_version }}
          distribution: 'adopt'
          cache: 'maven'

      # - name: Update version on pom.xml
      #   if: ${{ inputs.language == "java" }}
      #   run: |
      #     [[ -n ${{ inputs.app_version }} ]] && mvn $MAVEN_CLI_OPTS release:update-versions -DdevelopmentVersion=${{ inputs.app_version }}

      - name: Run build
        if: ${{ inputs.language == "java" }}
        run: mvn $MAVEN_CLI_OPTS -Dmaven.test.skip=true clean package

      - name: Archive artifact
        if: ${{ inputs.language == "java" }}
        uses: actions/upload-artifact@v3
        with:
          path: target/*.jar
          retention-days: 1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        if: ${{ inputs.language == "javascript" }}
        with:
          node-version: ${{ inputs.node_version }}
          cache: ${{ inputs.package_manager }}

      - name: Install dependencies
        if: ${{ inputs.language == "javascript" }}
        run: |
          [[ ${{ inputs.package_manager }} == 'npm' ]] && npm ci --prefer-offline --ignore-scripts
          [[ ${{ inputs.package_manager }} == 'yarn' ]] && yarn install --frozen-lockfile --ignore-scripts

      # - name: Update version on package.json
      #   if: ${{ inputs.language == "javascript" }}
      #   run: |
      #     npm version --git-tag-version=false ${{ inputs.app_version }}

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        if: ${{ inputs.language == "php" }}
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        if: ${{ inputs.language == "php" }}
        with:
          php_version: ${{ inputs.php_version }}
          version: latest
          dev: no
          args: --ignore-platform-reqs