name: Dynamic Application Security Test

on:
  workflow_call:
    inputs:
      app_url:
        type: string
        required: false
        default: ""

jobs:
  dast:
    name: DAST
    runs-on: live
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: ${{ inputs.app_url }}