name: Deliver workflow

on:
  workflow_call:
    inputs:
      app_version:
        type: string
        required: false
        default: ""
      image_repository:
        type: string
        required: false
        default: ""
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

env:
  AWS_REGION: us-east-1

jobs:
  release:
    name: Release
    if: ${{ github.ref_name == github.event.repository.default_branch }}
    runs-on: live
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.app_version }}

  publish_docker:
    name: Publish Docker
    runs-on: live
    steps:
      - name: Docker | Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders

      - name: Docker | Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: container-image

      - name: Docker push
        run: |
          docker load --input image.tar
          docker push ${{ steps.login_ecr.outputs.registry }}/${{ inputs.image_repository }}:${{ inputs.app_version }}