name: Docker CI

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      promote_image_version:
        type: boolean
        required: false
        default: false
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
    outputs:
      image_tags:
        value: ${{ jobs.build.outputs.image_tags }}

env:
  ENV: ${{ inputs.env }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      aws_account_id: ${{ steps.env.outputs.aws_account_id }}
      aws_region: ${{ steps.env.outputs.aws_region }}
      ecr_registry: ${{ steps.env.outputs.ecr_registry }}
      aws_iam_role: ${{ steps.env.outputs.aws_iam_role }}
      image_tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set env variables
        id: env
        run: |
          declare -A AWS_ACCOUNTS_IDS AWS_REGIONS
          AWS_ACCOUNTS_IDS=([dev]=180811438061 [stage]=406026015868 [live]=114395709799)
          AWS_REGIONS=([dev]=us-east-2 [stage]=us-east-2 [live]=us-east-2)
          AWS_ACCOUNT_ID=${AWS_ACCOUNTS_IDS[$ENV]}
          AWS_REGION=${AWS_REGIONS[$ENV]}

          ECR_REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
          ECR_REPOSITORY=${GITHUB_REPOSITORY#*/}
          AWS_IAM_ROLE=arn:aws:iam::${AWS_ACCOUNT_ID}:role/CrossAccount-Global-Developer

          echo "::set-output name=aws_account_id::${AWS_ACCOUNT_ID}"
          echo "::set-output name=aws_region::${AWS_REGION}"
          echo "::set-output name=ecr_registry::${ECR_REGISTRY}"
          echo "::set-output name=ecr_repository::${ECR_REPOSITORY}"
          echo "::set-output name=aws_iam_role::${AWS_IAM_ROLE}"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: "${{ steps.env.outputs.ecr_registry }}/${{ steps.env.outputs.ecr_repository }}"
          tags: |
            type=ref,suffix=-{{sha}},event=branch
            type=ref,prefix=pr-,suffix=-{{sha}},event=pr
            type=semver,pattern={{version}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ steps.env.outputs.aws_region }}
          role-skip-session-tagging: true
          role-to-assume: ${{ steps.env.outputs.aws_iam_role }}
          role-duration-seconds: 1200
          role-session-name: GitHubActionsBuildSession
          mask-aws-account-id: false

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: ${{ steps.env.outputs.aws_account_id }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=/tmp/${{ steps.env.outputs.ecr_repository }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.env.outputs.ecr_repository }}
          path: /tmp/${{ steps.env.outputs.ecr_repository }}.tar
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
                  
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ needs.build.outputs.aws_region }}
          role-skip-session-tagging: true
          role-to-assume: ${{ needs.build.outputs.aws_iam_role }}
          role-duration-seconds: 1200
          role-session-name: GitHubActionsBuildSession
          mask-aws-account-id: false

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: ${{ needs.build.outputs.aws_account_id }}

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.build.outputs.ecr_repository }}
          path: /tmp
                  
      - name: Push image tags
        run: |
          docker load --input /tmp/${{ needs.build.outputs.ecr_repository }}.tar

          aws ecr describe-repositories \
            --registry-id ${{ needs.build.outputs.aws_account_id }} \
            --repository-names ${{ needs.build.outputs.ecr_repository }} 2> /dev/null \
            || aws ecr create-repository --repository-name ${{ needs.build.outputs.ecr_repository }} --image-scanning-configuration scanOnPush=true

          for IMAGE_TAG in ${{ needs.build.outputs.image_tags }}; do
            docker push ${IMAGE_TAG}
          done
