name: Docker CI

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      skip_tests:
        type: boolean
        required: false
        default: false
      skip_lint:
        type: boolean
        required: false
        default: false
      promote_image_version:
        type: boolean
        required: false
        default: false
      promote_from_env:
        type: string
        required: false
        default: stg
      promote_from_branch:
        type: string
        required: false
        default: main
      build_args:
        type: string
        required: false
        default: ""
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
    outputs:
      image_tags:
        value: ${{ jobs.build.outputs.image_tags }}

env:
  ENV: ${{ inputs.env }}
  FROM_ENV: ${{ inputs.promote_from_env }}

jobs:
  build:
    runs-on: ${{ inputs.env }}
    outputs:
      aws_account_id: ${{ steps.env.outputs.aws_account_id }}
      aws_region: ${{ steps.env.outputs.aws_region }}
      ecr_registry: ${{ steps.env.outputs.ecr_registry }}
      ecr_repository: ${{ steps.env.outputs.ecr_repository }}
      aws_iam_role: ${{ steps.env.outputs.aws_iam_role }}
      image_tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders

      - name: Set env variables
        id: env
        run: |
          declare -A AWS_ACCOUNTS_IDS AWS_REGIONS
          AWS_ACCOUNTS_IDS=([dev]=180811438061 [stg]=406026015868 [live]=114395709799)
          AWS_REGIONS=([dev]=us-east-2 [stg]=us-east-2 [live]=us-east-2)

          AWS_ACCOUNT_ID=${AWS_ACCOUNTS_IDS[$ENV]}
          AWS_REGION=${AWS_REGIONS[$ENV]}

          ECR_REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
          ECR_REPOSITORY=${GITHUB_REPOSITORY#*/}
          AWS_IAM_ROLE=arn:aws:iam::${AWS_ACCOUNT_ID}:role/CrossAccount-Global-Developer

          echo "::set-output name=aws_account_id::${AWS_ACCOUNT_ID}"
          echo "::set-output name=aws_region::${AWS_REGION}"
          echo "::set-output name=ecr_registry::${ECR_REGISTRY}"
          echo "::set-output name=ecr_repository::${ECR_REPOSITORY}"
          echo "::set-output name=aws_iam_role::${AWS_IAM_ROLE}"

          FROM_AWS_ACCOUNT_ID=${AWS_ACCOUNTS_IDS[$FROM_ENV]}
          FROM_AWS_REGION=${AWS_REGIONS[$FROM_ENV]}
          FROM_ECR_REGISTRY=${FROM_AWS_ACCOUNT_ID}.dkr.ecr.${FROM_AWS_REGION}.amazonaws.com
          FROM_AWS_IAM_ROLE=arn:aws:iam::${FROM_AWS_ACCOUNT_ID}:role/CrossAccount-Global-Developer

          echo "::set-output name=from_aws_account_id::${FROM_AWS_ACCOUNT_ID}"
          echo "::set-output name=from_aws_region::${FROM_AWS_REGION}"
          echo "::set-output name=from_ecr_registry::${FROM_ECR_REGISTRY}"
          echo "::set-output name=from_aws_iam_role::${FROM_AWS_IAM_ROLE}"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: "${{ steps.env.outputs.ecr_registry }}/${{ steps.env.outputs.ecr_repository }}"
          tags: |
            type=ref,suffix=-{{sha}},event=branch
            type=ref,prefix=pr-,suffix=-{{sha}},event=pr
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ steps.env.outputs.aws_region }}
          role-skip-session-tagging: true
          role-to-assume: ${{ steps.env.outputs.aws_iam_role }}
          role-duration-seconds: 1200
          role-session-name: GitHubActionsBuildSession
          mask-aws-account-id: false
          
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: ${{ steps.env.outputs.aws_account_id }}

      - name: Build image
        if: ${{ ! inputs.promote_image_version }}
        uses: docker/build-push-action@v2
        with:
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          build-args: ${{ inputs.build_args }}
          outputs: type=docker,dest=/tmp/${{ steps.env.outputs.ecr_repository }}.tar

      - name: Configure AWS credentials
        if: ${{ inputs.promote_image_version }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ steps.env.outputs.from_aws_region }}
          role-skip-session-tagging: true
          role-to-assume: ${{ steps.env.outputs.from_aws_iam_role }}
          role-duration-seconds: 1200
          role-session-name: GitHubActionsBuildSession
          mask-aws-account-id: false
          
      - name: Login to Amazon ECR
        if: ${{ inputs.promote_image_version }}
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: ${{ steps.env.outputs.from_aws_account_id }}

      - name: Promote image
        if: ${{ inputs.promote_image_version }}
        run: |
          SRC_IMAGE_TAG=${{ steps.env.outputs.from_ecr_registry }}/${{ steps.env.outputs.ecr_repository }}:${{ inputs.promote_from_branch }}-${GITHUB_SHA:0:7}
          docker pull ${SRC_IMAGE_TAG}
          for IMAGE_TAG in $(echo "${{ steps.meta.outputs.tags }}" | tr '\n' ' '); do
            docker tag ${SRC_IMAGE_TAG} ${IMAGE_TAG}
          done
          docker save $(echo "${{ steps.meta.outputs.tags }}" | tr '\n' ' ') -o /tmp/${{ steps.env.outputs.ecr_repository }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.env.outputs.ecr_repository }}
          path: /tmp/${{ steps.env.outputs.ecr_repository }}.tar
          retention-days: 1

  test:
    runs-on: ${{ inputs.env }}
    needs:
      - build
    if: ${{ !inputs.skip_tests }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders

      - name: Linting
        uses: docker/build-push-action@v2
        if: ${{ !inputs.skip_lint }}
        with:
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          target: linting

      - name: Tests
        uses: docker/build-push-action@v2
        with:
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          target: tests

  release:
    runs-on: ${{ inputs.env }}
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
                  
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ needs.build.outputs.aws_region }}
          role-skip-session-tagging: true
          role-to-assume: ${{ needs.build.outputs.aws_iam_role }}
          role-duration-seconds: 1200
          role-session-name: GitHubActionsBuildSession
          mask-aws-account-id: false

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: ${{ needs.build.outputs.aws_account_id }}

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.build.outputs.ecr_repository }}
          path: /tmp
                  
      - name: Push image tags
        run: |
          docker load --input /tmp/${{ needs.build.outputs.ecr_repository }}.tar

          aws ecr describe-repositories \
            --registry-id ${{ needs.build.outputs.aws_account_id }} \
            --repository-names ${{ needs.build.outputs.ecr_repository }} 2> /dev/null \
            || aws ecr create-repository --repository-name ${{ needs.build.outputs.ecr_repository }} --image-scanning-configuration scanOnPush=true

          for IMAGE_TAG in $(echo "${{ needs.build.outputs.image_tags }}" | tr '\n' ' '); do
            docker push ${IMAGE_TAG}
          done
