name: Docker CI

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        default: us-east-1
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    outputs:
      IMAGE_TAG:
        value: ${{ steps.create_repository.outputs.image_tag }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@v1
                  
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check if registry exist if dont create it
        id: create_repository
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          ECR_REGISTRY: ${{ steps.login_ecr.outputs.registry }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          SHORT_COMMIT_SHA=${COMMIT_SHA:0:7}
          ECR_REPOSITORY=${GITHUB_REPOSITORY#*/}
          aws ecr describe-repositories --repository-names ${ECR_REPOSITORY} || aws ecr create-repository --repository-name ${ECR_REPOSITORY} --image-scanning-configuration scanOnPush=true
          
          echo "::set-output name=repository::${ECR_REGISTRY}/${ECR_REPOSITORY}"
          echo "::set-output name=image_tag::${{ github.ref_name }}-${SHORT_COMMIT_SHA}"

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          tags: |
            ${{ steps.create_repository.outputs.repository }}:${{ steps.create_repository.outputs.image_tag }}
            ${{ steps.create_repository.outputs.repository }}:latest
          push: true
