name: E2E tests

on:
  workflow_call:
    inputs:
      project_language:
        type: string
        required: false
        default: ""
      jdk_version:
        type: string
        required: false
        default: "11"
      node_package_manager:
        type: string
        required: false
        default: 'yarn'
      node_version:
        type: string
        required: false
        default: "lts/*"
    secrets:
      maven_settings_file:
        required: false

jobs:
  e2e_tests:
    name: E2E tests
    runs-on: live
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      ###### Java dependencies

      - name: Java | Create settings.xml file
        run: echo ${{ secrets.maven_settings_file }} | base64 -d > settings.xml

      - name: Java | Set up JDK
        uses: actions/setup-java@v3
        if: ${{ inputs.project_language == 'java' }}
        with:
          java-version: ${{ inputs.jdk_version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Java | Run test
        if: ${{ inputs.project_language == 'java' }}
        env:
          MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2- Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Djava.awt.headless=true"
          MAVEN_CLI_OPTS: "-B -e -fae -V -s settings.xml"
        run: mvn $MAVEN_CLI_OPTS e2e-tests

      ###### Javascript dependencies

      - name: Javascript | Setup Node.js
        uses: actions/setup-node@v3
        if: ${{ inputs.project_language == 'javascript' }}
        with:
          node-version: ${{ inputs.node_version }}
          cache: ${{ inputs.node_package_manager }}

      - name: Javascript | Install dependencies
        if: ${{ inputs.project_language == 'javascript' }}
        run: |
          [[ ${{ inputs.node_package_manager }} == 'npm' ]] && npm ci --prefer-offline --ignore-scripts
          [[ ${{ inputs.node_package_manager }} == 'yarn' ]] && yarn install --frozen-lockfile --ignore-scripts

      - name: Javascript | Run test
        if: ${{ inputs.project_language == 'javascript' }}
        run: |
          [[ ${{ inputs.node_package_manager }} == 'npm' ]] && npm run test:e2e
          [[ ${{ inputs.node_package_manager }} == 'yarn' ]] && yarn run test:e2e