name: EKS CD

on:
  workflow_call:
    inputs:
      helm_charts_path:
        type: string
        required: true
      project_name:
        type: string
        required: true
      project_namemespace:
        type: string
        required: true
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

jobs:
  deploy:
    name: deploy
    runs-on: live
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name : machine echo env
        env : { CONTENT : "${{ toJson(env) }}" }
        run : "echo $CONTENT"

      - name : machine echo secrets
        env : { CONTENT : "${{ toJson(secrets) }}" }
        run : "echo $CONTENT"

      - name : machine echo github
        env : { CONTENT : "${{ toJson(github) }}" }
        run : "echo $CONTENT"