name: Image scanning

on:
  workflow_call:
    inputs:
      docker_image:
        type: string
        required: false
        default: ""

jobs:
  image_scanning:
    name: Docker image scanning
    runs-on: live
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: container-image

      - name: Load image
        run: docker load --input image.tar

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: ${{ inputs.docker_image }}
          fail-build: true