name: Image scanning

on:
  workflow_call:
    inputs:
      docker_image:
        type: string
        required: false
        default: ""

jobs:
  image_scanning:
    name: Docker image scanning
    runs-on: live
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: container-image

      - name: Load image
        run: |
          docker load --input image.tar
          docker images
          docker tag ${{ inputs.docker_image }} localbuild/testimage:latest

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: localbuild/testimage:latest
          fail-build: true