name: Imperva purge cache

on:
  workflow_call:
    inputs:
      break:
        type: string
        default: 60
      site_id:
        type: string
        required: true
        description: |
          www.clickbus.com.br (50692396)
          www.grupoj3.com.br (46407632)
          whitelabels.clickbus.com.br (39358891)
          api-waf.clickbus.com (99257314)
    secrets:
      imperva_api_key:
        required: true
      imperva_api_id:
        required: true

jobs:
  cache:
    runs-on: live
    steps:
      - name: Purge cache Imperva
        run: |
          sleep ${{ inputs.break }}
          site_id="${{ inputs.site_id }}"
          for id  in  $site_id; do
            curl -X 'POST' \
              "https://my.imperva.com/api/prov/v1/sites/cache/purge?site_id=$id" \
              -H "accept: application/json" \
              -H "x-API-Key: ${{ secrets.imperva_api_key }}" \
              -H "x-API-Id: ${{ secrets.imperva_api_id }}" \
              -d ""
          done
        shell: bash
          