name: Kubernetes Deployment

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      image_tags:
        type: string
        required: true
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

env:
  ENV: ${{ inputs.env }}
  AWS_ACCOUNT_ID_DEV: 180811438061
  AWS_ACCOUNT_ID_STAGE: 406026015868
  AWS_ACCOUNT_ID_LIVE: 114395709799
  AWS_REGION_DEV: us-east-2 
  AWS_REGION_STAGE: us-east-2
  AWS_REGION_LIVE: us-east-2
  EKS_CLUSTER_NAME_DEV: k0-dev-clickbus-net
  EKS_CLUSTER_NAME_STAGE: k0-stg-clickbus-net
  EKS_CLUSTER_NAME_LIVE: k0-live-clickbus-net

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        id: set_env
        run: |
          AWS_ACCOUNT_ID=AWS_ACCOUNT_ID_${ENV^^}
          AWS_ACCOUNT_ID=${!AWS_ACCOUNT_ID}
          AWS_REGION=AWS_REGION_${ENV^^}
          AWS_REGION=${!AWS_REGION}
          EKS_CLUSTER_NAME=EKS_CLUSTER_NAME_${ENV^^}
          EKS_CLUSTER_NAME=${!EKS_CLUSTER_NAME}

          echo "AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}" >> $GITHUB_ENV
          echo "AWS_REGION=${AWS_REGION}" >> $GITHUB_ENV
          echo "EKS_CLUSTER_NAME=${EKS_CLUSTER_NAME}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.9.0

      - name: Helm upgrade
        run: |
          IMAGE_TAGS=(${{ inputs.image_tags }})
          ECR_REPOSITORY=${FIRST_IMAGE_TAG[0]%:*}
          IMAGE_TAG=${FIRST_IMAGE_TAG[0]#*:}
          RELEASE_NAME=${GITHUB_REPOSITORY#*/}
          NAMESPACE=${RELEASE_NAME}
          CHART_PATH=charts/${RELEASE_NAME}

          aws eks update-kubeconfig --name ${EKS_CLUSTER_NAME} --region ${AWS_REGION} --role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/${EKS_CLUSTER_NAME}-AmazonEKSAdmin

          helm upgrade --install ${RELEASE_NAME} ${CHART_PATH} \
            --create-namespace --namespace ${NAMESPACE} \
            --values ${CHART_PATH}/environments/${ENV}/values.yaml \
            --set image.repository=${ECR_REPOSITORY} --set image.tag=${IMAGE_TAG}
