name: Kubernetes Deployment

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      weight:
        type: string
        required: false
        default: '100'
      image_tags:
        type: string
        required: false
        default: ''
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: quay.io/roboll/helmfile:v0.143.1
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v2

      - name: Set ci_properties
        id: ci_properties
        env:
          ENVIRONMENT: ${{ inputs.env }}
        run: |
          declare -A AWS_ACCOUNT_ID AWS_REGION
          
          AWS_ACCOUNT_ID[dev]=180811438061
          AWS_ACCOUNT_ID[stage]=406026015868
          AWS_ACCOUNT_ID[live]=114395709799

          AWS_REGION[dev]=us-east-2
          AWS_REGION[stage]=us-east-2
          AWS_REGION[live]=us-east-2

          ROLE_ARN=arn:aws:iam::${AWS_ACCOUNT_ID[$ENVIRONMENT]}:role/CrossAccount-Global-Developer

          echo "::set-output name=aws_account_id::${AWS_ACCOUNT_ID[$ENVIRONMENT]}"
          echo "::set-output name=aws_region::${AWS_REGION[$ENVIRONMENT]}"
          echo "::set-output name=role_arn::${ROLE_ARN}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ steps.ci_properties.outputs.aws_region }}

      - name: Helm upgrade
        env:
          ENVIRONMENT: ${{ inputs.env }}
        run: |
          declare -A EKS_CLUSTER_NAME
          
          RELEASE_NAME=${GITHUB_REPOSITORY#*/}
          NAMESPACE=${RELEASE_NAME}
          CHART_PATH=charts/${RELEASE_NAME}

          EKS_CLUSTER_NAME[dev]=k0-dev-clickbus-net
          EKS_CLUSTER_NAME[stage]=k0-stg-clickbus-net
          EKS_CLUSTER_NAME[live]=k0-live-clickbus-net

          aws eks update-kubeconfig --name ${EKS_CLUSTER_NAME[$ENVIRONMENT]} --region ${{ steps.ci_properties.outputs.aws_region }} --role-arn ${{ steps.ci_properties.outputs.role_arn }}

          echo helm upgrade --install ${RELEASE_NAME} ${CHART_PATH} \
            --create-namespace --namespace ${NAMESPACE} \
            --reuse-values --values values.${ENVIRONMENT}.yaml \
            --set image.tag=${{ inputs.image_tags }}