name: Maven release prepare

on:
  workflow_call:
    inputs:
      gitversion:
        type: string
        required: true
      jdk_version:
        type: string
        required: false
        default: 11
    secrets:
      git_access_token:
        required: true
      maven_settings:
        required: true
      nexus_username:
        required: true
      nexus_password:
        required: true

env:
  MAVEN_CLI_OPTS: "-B -e -fae -V"
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  NEXUS_USERNAME: ${{ secrets.nexus_username }}
  NEXUS_PASSWORD: ${{ secrets.nexus_password }}

jobs:
  release_prepare:
    name: release prepare
    runs-on: live
    if: ${{ github.ref_name == github.event.repository.default_branch }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.git_access_token }}

      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.jdk_version }}
          distribution: 'temurin'
          cache: 'maven'
          overwrite-settings: false

      - name: create settings.xml
        run: echo ${{ secrets.maven_settings }} | base64 -d > ~/.m2/settings.xml

      - name: release prepare
        id: release_prepare
        run: |
          RELEASE_VERSION=$(echo '${{ inputs.gitversion }}' | jq -r '.SemVer')
          ./mvnw $MAVEN_CLI_OPTS org.codehaus.mojo:versions-maven-plugin:2.11.0:set -DnewVersion=${RELEASE_VERSION}
          ./mvnw $MAVEN_CLI_OPTS org.codehaus.mojo:versions-maven-plugin:2.11.0:set-property -Dproperty=revision -DnewVersion=${RELEASE_VERSION}
          ./mvnw $MAVEN_CLI_OPTS org.codehaus.mojo:versions-maven-plugin:2.11.0:commit
          git config user.email "github-actions@clickbus.com"
          git config user.name "Github Actions"
          git commit -a -m "chore: release v$RELEASE_VERSION"
          git tag v$RELEASE_VERSION
          git push origin v$RELEASE_VERSION

      - name: bump version
        run: |
          ./mvnw $MAVEN_CLI_OPTS build-helper:parse-version org.codehaus.mojo:versions-maven-plugin:2.11.0:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT
          ./mvnw $MAVEN_CLI_OPTS build-helper:parse-version org.codehaus.mojo:versions-maven-plugin:2.11.0:set-property -Dproperty=revision -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion}-SNAPSHOT
          ./mvnw $MAVEN_CLI_OPTS org.codehaus.mojo:versions-maven-plugin:2.11.0:commit
          VERSION=$(./mvnw $MAVEN_CLI_OPTS org.apache.maven.plugins:maven-help-plugin:3.3.0:evaluate -Dexpression=project.version -q -DforceStdout)
          git config user.email "github-actions@clickbus.com"
          git config user.name "Github Actions"
          git commit -a -m "chore: bump version to $VERSION [skip ci]"
          git push