name: PHP CI

on:
  workflow_call:
    inputs:
      node_version:
        type: string
        required: true
      package_disabled:
        type: boolean
        required: false
        default: false
      environment:
        type: string
        required: true
    secrets:
      git_access_token:
        required: true
      sonar_token:
        required: true

env:
  REPORT_CODESNIFFER: "phpunit.coverage.xml"
  REPORT_PHPUNIT: "phpunit.xml" 
  COVERAGE_JAVASCRIPT: "lcov.info"
  SONAR_HOST_URL: "https://sonar.clickbus.net"
  SONAR_TOKEN: ${{ secrets.sonar_token }}

jobs:
  code_sniffer:
    name: PHP_CodeSniffer
    runs-on: ${{ inputs.environment }}
    if: ${{ (github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')) || (github.event_name == 'push' && github.ref_type == 'tag') }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: setup composer
        run: composer config --global github-oauth.github.com ${{ secrets.git_access_token }}

      - name: install php dependencies
        uses: "ramsey/composer-install@v2"
        with:
          custom-cache-suffix: ${{ github.sha }}

      - name: code_sniffer
        continue-on-error: true
        run: ./vendor/bin/phpcs

  phpunit:
    name: PHPUnit
    runs-on: ${{ inputs.environment }}
    if: ${{ (github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')) || (github.event_name == 'push' && github.ref_type == 'tag') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup composer
        run: composer config --global github-oauth.github.com ${{ secrets.git_access_token }}

      - name: install php dependencies
        uses: "ramsey/composer-install@v2"
        with:
          custom-cache-suffix: ${{ github.sha }}

      - name: phpunit
        continue-on-error: true
        run: php vendor/bin/phpunit -c app

      - name: archive PHP_CodeSniffer report
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REPORT_CODESNIFFER }}
          path: ./reports/${{ env.REPORT_CODESNIFFER }}

      - name: archive unit tests report
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REPORT_PHPUNIT }}
          path: ./reports/${{ env.REPORT_PHPUNIT }}

  javascript_unit_tests:
    name: javascript unit tests
    runs-on: ${{ inputs.environment }}
    if: ${{ (github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')) || (github.event_name == 'push' && github.ref_type == 'tag') }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          cache: npm

      - name: install Yarn
        run: npm install --global yarn

      - name: setup Yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          cache: yarn

      - name: install javascript dependencies
        run: yarn install --ignore-engines

      - name: execute unit tests
        continue-on-error: true
        run: yarn test -- --coverage

      - name: upload report artfact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.COVERAGE_JAVASCRIPT }}
          path: ./coverage/${{ env.COVERAGE_JAVASCRIPT }}

  sonarqube:
    name: sonarqube
    runs-on: ${{ inputs.environment }}
    needs:
      - code_sniffer
      - phpunit
      - javascript_unit_tests
    if: ${{ (github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')) || (github.event_name == 'push' && github.ref_type == 'tag') }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: download php code sniffer report
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.REPORT_CODESNIFFER }}
          path: ./reports/

      - name: download php unit tests report
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.REPORT_CODESNIFFER }}
          path: ./reports/

      - name: download javascript unit tests report
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.COVERAGE_JAVASCRIPT }}
          path: ./coverage/

      - name: set sonar parameters
        id: set_sonar_parameters
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            SONAR_PARAMETERS="$SONAR_PARAMETERS -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} -Dsonar.pullrequest.github.repository=$GITHUB_REPOSITORY"
          fi
          echo "args=$SONAR_PARAMETERS" >> $GITHUB_OUTPUT

      - name: sonarqube scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            ${{ steps.set_sonar_parameters.outputs.args }}

      - name: sonarqube quality gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        continue-on-error: true

  package:
    name: package
    runs-on: ${{ inputs.environment }}
    needs:
      - sonarqube
    if: ${{ !inputs.package_disabled && ((github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')) || (github.event_name == 'push' && github.ref_type == 'tag')) }}
    env:
      SYMFONY_ENV: brazil_prod
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup composer
        run: composer config --global github-oauth.github.com ${{ secrets.git_access_token }}

      - name: install php dependencies
        uses: "ramsey/composer-install@v2"
        with:
          custom-cache-suffix: ${{ github.sha }}
          composer-options: "--verbose --prefer-dist --optimize-autoloader --no-dev --no-interaction"

      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          cache: npm

      - name: install Yarn
        run: npm install --global yarn

      - name: setup Yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          cache: yarn

      - name: install dependency with yarn
        run: yarn install --ignore-engines

      - name: install dependency with bower
        run: node_modules/bower/bin/bower install

      - name: install dependency with gulp
        run: node_modules/gulp/bin/gulp.js build

      - name: Cleanup ./vendor/
        run: find ./vendor -name ".git" -type d | xargs rm -rf

      - name: Package the app
        run: tar --ignore-failed-read -zcvf app-artifact.tar.gz app bin features src vendor web

      - name: archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-artifact
          path: app-artifact.tar.gz

  release:
    name: release
    runs-on: ${{ inputs.environment }}
    needs:
      - package
    if: ${{ always() && (needs.package.result == 'success' || needs.package.result == 'skipped') && (github.event_name == 'push' && github.ref_type == 'tag') }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: create github release
        uses: softprops/action-gh-release@v1