name: Release stage

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        default: ""

jobs:
  release:
    name: Release
    runs-on: live
    if: ${{ github.ref_name == github.event.repository.default_branch && github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}