name: Security workflow

on:
  workflow_call:
    inputs:
      image_scanning_disabled:
        type: boolean
        required: false
        default: false
      image:
        type: string
        required: true
    secrets:
      sonar_token:
        required: false
        default: ""

env:
  RUNS_ON: k8s-live

jobs:
  sonarqube_scanning:
    name: SonarQube Scanning
    runs-on: ${{ env.RUNS_ON }}
    if: ${{ !inputs.sonarqube_scanning_disabled }}
    steps:
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: "https://sonar.clickbus.net"
          SONAR_TOKEN: ${{ secrets.sonar_token }}

      - name: SonarQube Quality Gate
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_HOST_URL: "https://sonar.clickbus.net"
          SONAR_TOKEN: ${{ secrets.sonar_token }}

  image_scanning:
    name: Container Image Scanning
    runs-on: ${{ env.RUNS_ON }}
    if: ${{ !inputs.image_scanning_disabled }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-artifact

      - name: Load image
        run: docker load --input image.tar

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: ${{ inputs.image }}
          path: .
          fail-build: true