name: Security workflow

on:
  workflow_call:
    inputs:
      docker_image:
        type: string
        required: false
        default: ""
      sast_disabled:
        type: boolean
        required: false
        default: false
      image_scanning_disabled:
        type: boolean
        required: false
        default: false
      dast_disabled:
        type: boolean
        required: false
        default: false
      app_url:
        type: string
        required: false
        default: ""
    secrets:
      sonar_token:
        required: true

jobs:
  static_application_security_testing:
    name: SAST
    runs-on: live
    if: ${{ !inputs.sast_disabled }}
    steps:
      - name: Download test reports
        uses: actions/download-artifact@v3
        with:
          name: test-reports

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: "https://sonar.clickbus.net"
          SONAR_TOKEN: ${{ secrets.sonar_token }}

      - name: SonarQube Quality Gate
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_HOST_URL: "https://sonar.clickbus.net"
          SONAR_TOKEN: ${{ secrets.sonar_token }}

  image_scanning:
    name: Docker image scanning
    runs-on: live
    if: ${{ !inputs.image_scanning_disabled }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: container-image

      - name: Load image
        run: docker load --input image.tar

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: ${{ inputs.docker_image }}
          path: .
          fail-build: true

  dynamic_application_security_test:
    name: DAST
    runs-on: live
    if: ${{ !inputs.dast_disabled }}
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: ${{ inputs.app_url }}