name: Setup Workflow

on:
  workflow_call:
    outputs:
      project_name:
        value: ${{ jobs.project_properties.outputs.project_name }}
      gitversion:
        value: ${{ jobs.project_properties.outputs.gitversion }}

jobs:
  project_properties:
    name: project properties
    runs-on: live
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup Node.js
        uses: actions/setup-node@v3
        if: ${{ (github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')) || github.ref_name == github.event.repository.default_branch }}
        with:
          node-version: latest

      - name: lint commit
        if: ${{ (github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')) || github.ref_name == github.event.repository.default_branch }}
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional
          echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js

          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "${{ github.event.pull_request.title }}" | commitlint
          else
            echo "${{ github.event.head_commit.message }}" | commitlint
          fi

      - name: setup .NET cli
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
        
      - name: setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          additionalArguments: >
            /overrideconfig mode=Mainline
            /overrideconfig major-version-bump-message="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?(!:|:.*\\n\\n((.+\\n)+\\n)?BREAKING CHANGE:\\s.+)"
            /overrideconfig minor-version-bump-message="^(feat)(\\([\\w\\s-]*\\))?:"
            /overrideconfig patch-version-bump-message="^(build|chore|ci|docs|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?:"

      - name: setup project properties
        id: project_properties
        run: |
          echo "::set-output name=project_name::${GITHUB_REPOSITORY#*/}"
          echo "::set-output name=gitversion::{\"MajorMinorPatch\": \"${GITVERSION_MAJORMINORPATCH}\", \"EscapedBranchName\": \"${GITVERSION_ESCAPEDBRANCHNAME}\", \"ShortSha\": \"${GITVERSION_SHORTSHA}\"}"
    outputs:
      project_name: ${{ steps.project_properties.outputs.project_name }}
      gitversion: ${{ steps.project_properties.outputs.gitversion }}