name: Tests Workflow

on:
  workflow_call:
    inputs:
      jdk_version:
        type: string
        required: false
        default: 11
      project_buildpack:
        type: string
        required: false
        default: ''

jobs:
  maven_tests:
    if: ${{ inputs.project_buildpack == 'maven' }}
    uses: ./.github/workflows/maven-tests.yml
  gradle_tests:
    if: ${{ inputs.project_buildpack == 'gradle' }}
    uses: ./.github/workflows/gradle-tests.yml